# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nick Switzer
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Nick Switzer is a web developer based in Denver, Colorado.
  He specializes in front end development, site architecture 
  and Drupal themeing.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.nick-switzer.com" # the base hostname & protocol for your site
permalink: /weekly/:year/:month/:day/:title

# Build settings
markdown: kramdown
